version: '3.8'

services:
  backend:
    build: .
    container_name: ai_studio_backend
    ports:
      - "8000:8001"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FAL_KEY=${FAL_KEY}
      - PROJECT_NAME=AI Studio Backend
      - VERSION=1.0.0
      - API_V1_STR=/api/v1
    env_file:
      - .env
    restart: unless-stopped
